[2024-07-12T04:41:11.450+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vehicle_data_etl_DAG.run_events_etl scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T04:41:11.594+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vehicle_data_etl_DAG.run_events_etl scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T04:41:11.595+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 3
[2024-07-12T04:41:11.601+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_events_etl> on 2024-07-11 00:00:00+00:00
[2024-07-12T04:41:11.606+0000] {standard_task_runner.py:57} INFO - Started process 194 to run task
[2024-07-12T04:41:11.608+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'vehicle_data_etl_DAG', 'run_events_etl', 'scheduled__2024-07-11T00:00:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/events_dag.py', '--cfg-path', '/tmp/tmp1tnt0cvh']
[2024-07-12T04:41:11.611+0000] {standard_task_runner.py:85} INFO - Job 60: Subtask run_events_etl
[2024-07-12T04:41:11.645+0000] {task_command.py:410} INFO - Running <TaskInstance: vehicle_data_etl_DAG.run_events_etl scheduled__2024-07-11T00:00:00+00:00 [running]> on host 24dfc49a9e4f
[2024-07-12T04:41:11.711+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ilyas' AIRFLOW_CTX_DAG_ID='vehicle_data_etl_DAG' AIRFLOW_CTX_TASK_ID='run_events_etl' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T00:00:00+00:00'
[2024-07-12T04:41:11.713+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-07-12T04:41:11.714+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/etl/vehicle_data && python3 main.py']
[2024-07-12T04:41:11.721+0000] {subprocess.py:86} INFO - Output:
[2024-07-12T04:41:23.176+0000] {subprocess.py:93} INFO - 2024-07-12 04:41:23.175 | INFO     | kaggle_pipeline.extract:get_data:30 - Dataset downloaded and extracted directly.
[2024-07-12T04:41:23.182+0000] {subprocess.py:93} INFO - 2024-07-12 04:41:23.176 | INFO     | kaggle_pipeline.extract:get_data:32 - Dataset downloaded and extracted successfully.
[2024-07-12T04:41:24.165+0000] {subprocess.py:93} INFO - 2024-07-12 04:41:24.163 | INFO     | kaggle_pipeline.load:load_data:33 - Data loaded successfully from vehicle_data_sales/car_prices.csv
[2024-07-12T04:41:24.169+0000] {subprocess.py:93} INFO - 2024-07-12 04:41:24.168 | ERROR    | kaggle_pipeline.load:initialize_pg_table:54 - Error initializing table (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
[2024-07-12T04:41:24.170+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2024-07-12T04:41:24.174+0000] {subprocess.py:93} INFO - connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
[2024-07-12T04:41:24.174+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2024-07-12T04:41:24.174+0000] {subprocess.py:93} INFO - 
[2024-07-12T04:41:24.175+0000] {subprocess.py:93} INFO - (Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-07-12T04:41:25.023+0000] {subprocess.py:93} INFO - 2024-07-12 04:41:25.023 | INFO     | kaggle_pipeline.load:load_data:33 - Data loaded successfully from vehicle_data_sales/car_prices.csv
[2024-07-12T04:41:25.025+0000] {subprocess.py:93} INFO - 2024-07-12 04:41:25.025 | ERROR    | kaggle_pipeline.transform:transform_data_type:40 - Error transforming data 'timestamp'
[2024-07-12T04:41:25.041+0000] {subprocess.py:93} INFO - 2024-07-12 04:41:25.040 | ERROR    | kaggle_pipeline.load:insert_data_to_pg:64 - Data transformation failed
[2024-07-12T04:41:25.055+0000] {subprocess.py:93} INFO - Dataset URL: https://www.kaggle.com/datasets/syedanwarafridi/vehicle-sales-data
[2024-07-12T04:41:25.238+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-12T04:41:25.276+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=vehicle_data_etl_DAG, task_id=run_events_etl, execution_date=20240711T000000, start_date=20240712T044111, end_date=20240712T044125
[2024-07-12T04:41:25.327+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-07-12T04:41:25.346+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
