[2024-07-12T14:58:13.278+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vehicle_data_etl_DAG.run_events_etl manual__2024-07-12T14:54:19.829727+00:00 [queued]>
[2024-07-12T14:58:13.285+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vehicle_data_etl_DAG.run_events_etl manual__2024-07-12T14:54:19.829727+00:00 [queued]>
[2024-07-12T14:58:13.285+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 3
[2024-07-12T14:58:13.292+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_events_etl> on 2024-07-12 14:54:19.829727+00:00
[2024-07-12T14:58:13.297+0000] {standard_task_runner.py:57} INFO - Started process 1061 to run task
[2024-07-12T14:58:13.301+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'vehicle_data_etl_DAG', 'run_events_etl', 'manual__2024-07-12T14:54:19.829727+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/vehicle_data_dag.py', '--cfg-path', '/tmp/tmpggff42w_']
[2024-07-12T14:58:13.304+0000] {standard_task_runner.py:85} INFO - Job 75: Subtask run_events_etl
[2024-07-12T14:58:13.341+0000] {task_command.py:410} INFO - Running <TaskInstance: vehicle_data_etl_DAG.run_events_etl manual__2024-07-12T14:54:19.829727+00:00 [running]> on host 4f50c91679f1
[2024-07-12T14:58:13.412+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ilyas' AIRFLOW_CTX_DAG_ID='vehicle_data_etl_DAG' AIRFLOW_CTX_TASK_ID='run_events_etl' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T14:54:19.829727+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-12T14:54:19.829727+00:00'
[2024-07-12T14:58:13.414+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-07-12T14:58:13.415+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/etl/vehicle_data && python3 main.py']
[2024-07-12T14:58:13.424+0000] {subprocess.py:86} INFO - Output:
[2024-07-12T14:58:25.824+0000] {subprocess.py:93} INFO - 2024-07-12 14:58:25.821 | INFO     | kaggle_pipeline.extract:get_data:30 - Dataset downloaded and extracted directly.
[2024-07-12T14:58:25.826+0000] {subprocess.py:93} INFO - 2024-07-12 14:58:25.823 | INFO     | kaggle_pipeline.extract:get_data:32 - Dataset downloaded and extracted successfully.
[2024-07-12T14:58:26.944+0000] {subprocess.py:93} INFO - 2024-07-12 14:58:26.943 | INFO     | kaggle_pipeline.load:load_data:34 - Data loaded successfully from /opt/***/etl/vehicle_data/vehicle_data_sales/car_prices.csv
[2024-07-12T14:58:26.972+0000] {subprocess.py:93} INFO - 2024-07-12 14:58:26.971 | INFO     | kaggle_pipeline.load:initialize_pg_table:52 - Table vehicle_sales created successfully.
[2024-07-12T14:58:28.045+0000] {subprocess.py:93} INFO - 2024-07-12 14:58:28.043 | INFO     | kaggle_pipeline.load:load_data:34 - Data loaded successfully from /opt/***/etl/vehicle_data/vehicle_data_sales/car_prices.csv
[2024-07-12T14:58:29.061+0000] {subprocess.py:93} INFO - 2024-07-12 14:58:29.061 | INFO     | kaggle_pipeline.transform:transform_data_type:37 - Data type transformation is successful.
[2024-07-12T14:58:30.515+0000] {subprocess.py:97} INFO - Command exited with return code -9
[2024-07-12T14:58:30.619+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code -9.
[2024-07-12T14:58:30.634+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=vehicle_data_etl_DAG, task_id=run_events_etl, execution_date=20240712T145419, start_date=20240712T145813, end_date=20240712T145830
[2024-07-12T14:58:30.662+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 75 for task run_events_etl (Bash command failed. The command returned a non-zero exit code -9.; 1061)
[2024-07-12T14:58:30.725+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-07-12T14:58:30.764+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
