[2024-07-12T15:03:31.849+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vehicle_data_etl_DAG.run_events_etl manual__2024-07-12T14:54:19.829727+00:00 [queued]>
[2024-07-12T15:03:31.854+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vehicle_data_etl_DAG.run_events_etl manual__2024-07-12T14:54:19.829727+00:00 [queued]>
[2024-07-12T15:03:31.855+0000] {taskinstance.py:1308} INFO - Starting attempt 3 of 3
[2024-07-12T15:03:31.861+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_events_etl> on 2024-07-12 14:54:19.829727+00:00
[2024-07-12T15:03:31.864+0000] {standard_task_runner.py:57} INFO - Started process 1187 to run task
[2024-07-12T15:03:31.866+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'vehicle_data_etl_DAG', 'run_events_etl', 'manual__2024-07-12T14:54:19.829727+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/vehicle_data_dag.py', '--cfg-path', '/tmp/tmp6cua1be2']
[2024-07-12T15:03:31.867+0000] {standard_task_runner.py:85} INFO - Job 76: Subtask run_events_etl
[2024-07-12T15:03:31.891+0000] {task_command.py:410} INFO - Running <TaskInstance: vehicle_data_etl_DAG.run_events_etl manual__2024-07-12T14:54:19.829727+00:00 [running]> on host 4f50c91679f1
[2024-07-12T15:03:31.933+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ilyas' AIRFLOW_CTX_DAG_ID='vehicle_data_etl_DAG' AIRFLOW_CTX_TASK_ID='run_events_etl' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T14:54:19.829727+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-12T14:54:19.829727+00:00'
[2024-07-12T15:03:31.934+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-07-12T15:03:31.934+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/etl/vehicle_data && python3 main.py']
[2024-07-12T15:03:31.940+0000] {subprocess.py:86} INFO - Output:
[2024-07-12T15:03:44.441+0000] {subprocess.py:93} INFO - 2024-07-12 15:03:44.438 | INFO     | kaggle_pipeline.extract:get_data:30 - Dataset downloaded and extracted directly.
[2024-07-12T15:03:44.443+0000] {subprocess.py:93} INFO - 2024-07-12 15:03:44.440 | INFO     | kaggle_pipeline.extract:get_data:32 - Dataset downloaded and extracted successfully.
[2024-07-12T15:03:45.467+0000] {subprocess.py:93} INFO - 2024-07-12 15:03:45.466 | INFO     | kaggle_pipeline.load:load_data:34 - Data loaded successfully from /opt/***/etl/vehicle_data/vehicle_data_sales/car_prices.csv
[2024-07-12T15:03:45.476+0000] {subprocess.py:93} INFO - 2024-07-12 15:03:45.476 | INFO     | kaggle_pipeline.load:initialize_pg_table:52 - Table vehicle_sales created successfully.
[2024-07-12T15:03:46.319+0000] {subprocess.py:93} INFO - 2024-07-12 15:03:46.319 | INFO     | kaggle_pipeline.load:load_data:34 - Data loaded successfully from /opt/***/etl/vehicle_data/vehicle_data_sales/car_prices.csv
[2024-07-12T15:03:47.210+0000] {subprocess.py:93} INFO - 2024-07-12 15:03:47.209 | INFO     | kaggle_pipeline.transform:transform_data_type:37 - Data type transformation is successful.
[2024-07-12T15:03:49.187+0000] {subprocess.py:97} INFO - Command exited with return code -9
[2024-07-12T15:03:49.238+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code -9.
[2024-07-12T15:03:49.246+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=vehicle_data_etl_DAG, task_id=run_events_etl, execution_date=20240712T145419, start_date=20240712T150331, end_date=20240712T150349
[2024-07-12T15:03:49.268+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 76 for task run_events_etl (Bash command failed. The command returned a non-zero exit code -9.; 1187)
[2024-07-12T15:03:49.309+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-07-12T15:03:49.342+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
