[2024-07-12T14:17:19.280+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vehicle_data_etl_DAG.run_events_etl manual__2024-07-12T14:17:18.042692+00:00 [queued]>
[2024-07-12T14:17:19.289+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vehicle_data_etl_DAG.run_events_etl manual__2024-07-12T14:17:18.042692+00:00 [queued]>
[2024-07-12T14:17:19.291+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-07-12T14:17:19.315+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_events_etl> on 2024-07-12 14:17:18.042692+00:00
[2024-07-12T14:17:19.326+0000] {standard_task_runner.py:57} INFO - Started process 194 to run task
[2024-07-12T14:17:19.330+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'vehicle_data_etl_DAG', 'run_events_etl', 'manual__2024-07-12T14:17:18.042692+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/vehicle_data_dag.py', '--cfg-path', '/tmp/tmp8w_9xw7u']
[2024-07-12T14:17:19.339+0000] {standard_task_runner.py:85} INFO - Job 71: Subtask run_events_etl
[2024-07-12T14:17:19.385+0000] {task_command.py:410} INFO - Running <TaskInstance: vehicle_data_etl_DAG.run_events_etl manual__2024-07-12T14:17:18.042692+00:00 [running]> on host 4f50c91679f1
[2024-07-12T14:17:19.447+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ilyas' AIRFLOW_CTX_DAG_ID='vehicle_data_etl_DAG' AIRFLOW_CTX_TASK_ID='run_events_etl' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T14:17:18.042692+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-12T14:17:18.042692+00:00'
[2024-07-12T14:17:19.450+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-07-12T14:17:19.451+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/etl/vehicle_data && python3 main.py']
[2024-07-12T14:17:19.460+0000] {subprocess.py:86} INFO - Output:
[2024-07-12T14:17:29.855+0000] {subprocess.py:93} INFO - 2024-07-12 14:17:29.853 | INFO     | kaggle_pipeline.extract:get_data:30 - Dataset downloaded and extracted directly.
[2024-07-12T14:17:29.862+0000] {subprocess.py:93} INFO - 2024-07-12 14:17:29.854 | INFO     | kaggle_pipeline.extract:get_data:32 - Dataset downloaded and extracted successfully.
[2024-07-12T14:17:30.750+0000] {subprocess.py:93} INFO - 2024-07-12 14:17:30.750 | INFO     | kaggle_pipeline.load:load_data:33 - Data loaded successfully from /opt/***/etl/vehicle_data/vehicle_data_sales/car_prices.csv
[2024-07-12T14:17:30.753+0000] {subprocess.py:93} INFO - 2024-07-12 14:17:30.753 | ERROR    | kaggle_pipeline.load:initialize_pg_table:54 - Error initializing table (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
[2024-07-12T14:17:30.753+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2024-07-12T14:17:30.755+0000] {subprocess.py:93} INFO - connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
[2024-07-12T14:17:30.757+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2024-07-12T14:17:30.758+0000] {subprocess.py:93} INFO - 
[2024-07-12T14:17:30.758+0000] {subprocess.py:93} INFO - (Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-07-12T14:17:31.624+0000] {subprocess.py:93} INFO - 2024-07-12 14:17:31.624 | INFO     | kaggle_pipeline.load:load_data:33 - Data loaded successfully from /opt/***/etl/vehicle_data/vehicle_data_sales/car_prices.csv
[2024-07-12T14:17:32.030+0000] {subprocess.py:93} INFO - 2024-07-12 14:17:32.028 | ERROR    | kaggle_pipeline.transform:transform_data_type:40 - Error transforming data Cannot convert non-finite values (NA or inf) to integer
[2024-07-12T14:17:32.054+0000] {subprocess.py:93} INFO - 2024-07-12 14:17:32.053 | ERROR    | kaggle_pipeline.load:insert_data_to_pg:64 - Data transformation failed
[2024-07-12T14:17:32.070+0000] {subprocess.py:93} INFO - Dataset URL: https://www.kaggle.com/datasets/syedanwarafridi/vehicle-sales-data
[2024-07-12T14:17:32.331+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-12T14:17:32.376+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=vehicle_data_etl_DAG, task_id=run_events_etl, execution_date=20240712T141718, start_date=20240712T141719, end_date=20240712T141732
[2024-07-12T14:17:32.405+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-07-12T14:17:32.443+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
