[2024-07-11T18:22:17.859+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: events_etl_DAG.run_events_etl manual__2024-07-11T18:22:16.020509+00:00 [queued]>
[2024-07-11T18:22:17.864+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: events_etl_DAG.run_events_etl manual__2024-07-11T18:22:16.020509+00:00 [queued]>
[2024-07-11T18:22:17.864+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-07-11T18:22:17.871+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_events_etl> on 2024-07-11 18:22:16.020509+00:00
[2024-07-11T18:22:17.875+0000] {standard_task_runner.py:57} INFO - Started process 84 to run task
[2024-07-11T18:22:17.877+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'events_etl_DAG', 'run_events_etl', 'manual__2024-07-11T18:22:16.020509+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/events_dag.py', '--cfg-path', '/tmp/tmppj50p3tj']
[2024-07-11T18:22:17.878+0000] {standard_task_runner.py:85} INFO - Job 26: Subtask run_events_etl
[2024-07-11T18:22:17.903+0000] {task_command.py:410} INFO - Running <TaskInstance: events_etl_DAG.run_events_etl manual__2024-07-11T18:22:16.020509+00:00 [running]> on host 17f3ee23ca21
[2024-07-11T18:22:17.947+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ilyas' AIRFLOW_CTX_DAG_ID='events_etl_DAG' AIRFLOW_CTX_TASK_ID='run_events_etl' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T18:22:16.020509+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-11T18:22:16.020509+00:00'
[2024-07-11T18:22:17.948+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-07-11T18:22:17.948+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd ${AIRFLOW_PROJ_DIR}/etl/events && python3 main.py']
[2024-07-11T18:22:17.954+0000] {subprocess.py:86} INFO - Output:
[2024-07-11T18:22:17.961+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: /etl/events: No such file or directory
[2024-07-11T18:22:17.961+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-11T18:22:17.968+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-11T18:22:17.970+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=events_etl_DAG, task_id=run_events_etl, execution_date=20240711T182216, start_date=20240711T182217, end_date=20240711T182217
[2024-07-11T18:22:17.977+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 26 for task run_events_etl (Bash command failed. The command returned a non-zero exit code 1.; 84)
[2024-07-11T18:22:18.022+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-07-11T18:22:18.032+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
